webtalk_init -webtalk_dir /home/zhangshuai/develop/soft_core/vivado_project/test_core_add_saferegion/test_core_add_saferegion.sim/sim_1/behav/xsim.dir/picosoc_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Sat May 26 14:26:20 2018" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2015.4 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "1412921" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "LIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "e488f810-19ad-4a8c-a09a-32330bdd9fec" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "44d00ccf28994d619ee1cf1dd33405ff" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "6" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "LinuxMint" -context "user_environment"
webtalk_add_data -client project -key os_release -value "Linux Mint 17.3 Rosa" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i5-4590 CPU @ 3.30GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "3699.738 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "8.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "1 us" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "1" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.02_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "262344_KB" -context "xsim\\usage"
webtalk_transmit -clientid 166025550 -regid "" -xml /home/zhangshuai/develop/soft_core/vivado_project/test_core_add_saferegion/test_core_add_saferegion.sim/sim_1/behav/xsim.dir/picosoc_behav/webtalk/usage_statistics_ext_xsim.xml -html /home/zhangshuai/develop/soft_core/vivado_project/test_core_add_saferegion/test_core_add_saferegion.sim/sim_1/behav/xsim.dir/picosoc_behav/webtalk/usage_statistics_ext_xsim.html -wdm /home/zhangshuai/develop/soft_core/vivado_project/test_core_add_saferegion/test_core_add_saferegion.sim/sim_1/behav/xsim.dir/picosoc_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
